@echo off
echo Rebuilding and restarting API server and sync service containers with no cache...

echo Stopping containers...
docker-compose -f docker-compose.yml stop api-server sync-service

echo Rebuilding containers with no cache...
docker-compose -f docker-compose.yml build --no-cache api-server sync-service

echo Starting containers...
docker-compose -f docker-compose.yml up -d api-server sync-service

echo Checking container status...
docker-compose -f docker-compose.yml ps

echo Viewing logs (press Ctrl+C to exit)...
docker-compose -f docker-compose.yml logs -f api-server sync-service