@echo off
echo Activating virtual environment...
call .\venv\Scripts\activate
echo Installing required packages...
pip install -r requirements.txt
echo.
echo Starting the API server...
python api_server.py